### ISSUE TITLE
Not displaying correctly when given value from props

### ISSUE THREAD

**Issue by amhinson** [poberwong/react-native-switch-pro#1]
When I give the Switch a boolean value stored in props, the initial rendering of the switch is messing up:

<img width="165" alt="image 2017-01-28 at 5 52 49 pm" src="https://cloud.githubusercontent.com/assets/17091790/22400753/756206e4-e583-11e6-9190-5af07b98abe9.png">

Here is my code:

```
      <Switch
        width={60}
        height={30}
        circleColor={'white'}
        backgroundInactive={'rgba(255,255,255,0.2)'}
        backgroundActive={appColors.green}
        value={this.props.bookable}
        onSyncPress={value => this.props.inputChanged({ prop: 'bookable', value })}
      />
```

Any thoughts?

**Comment by poberwong** [comment]
Ok, I will fixed it today and thanks for your admiring. Finally, happy Chinese new year!!!

**Comment by poberwong** [comment]
![image](https://cloud.githubusercontent.com/assets/8554661/22401631/3d255eb4-e616-11e6-94e5-41cb23335602.png)
Like this, with this background, the problem didn't appear again with version of 0.39 and 0.40
Following is my code: 
```javascript
<Switch
  width={60}
  height={30}
  circleColor={'white'}
  backgroundInactive={'rgba(255,255,255,0.2)'}
  style={{marginTop: 20}}
  backgroundActive={'green'}
  value={this.props.bookable}
  onSyncPress={value => console.log('......: ', value)}
/>
```
There should be nothing wrong with value given. If undefined is delivered, the default value will work. so... could you provide more information for me ?

**Comment by amhinson** [comment]
I got it rendering correctly initially, but now it's acting strange whenever I click it, the circle goes across beyond the container, as seen below:

<img width="99" alt="image 2017-01-28 at 11 04 00 pm" src="https://cloud.githubusercontent.com/assets/17091790/22402036/3111565e-e5ae-11e6-8925-313b0af56445.png">
<img width="134" alt="image 2017-01-28 at 11 03 51 pm" src="https://cloud.githubusercontent.com/assets/17091790/22402038/353ef970-e5ae-11e6-9567-56cea8b0f5a9.png">

I think it has something to do with Redux. On my `onSyncPress` I have:
```
onSyncPress={value => this.props.bookableSwitch(value)}
```

and the action:
```
export const publicSwitch = (value) => {
  return {
    type: BOOKABLE_SWITCH,
    payload: value
  };
};
```
and reducer case:
```
case BOOKABLE_SWITCH:
      return { ...state, bookable: action.payload };
```
I'm checking the boolean value at every step and it seems to be correct all the way through, so I'm not sure why it is acting this way.

**Comment by amhinson** [comment]
Also, the active color appears to show the default green, but only shows my custom color briefly in transition.

**Comment by poberwong** [comment]
Ok，let's solve it together tomorrow because I have several articles to write. There could be some useful information:
1.The property `value` is just given to initialize the status of switch.
2. Changes of switch is self-controlled by inner state and you can get value in callback.
3. Don't try to control state of `Switch` with outer props because it will conflict with inner state.

**Comment by amhinson** [comment]
Would you be able to show me an example of how that might be implemented?

**Comment by poberwong** [comment]
I mean that you can't control switch with redux. If you have something to do when switch toggled, you can call the function in callback of Switch named `onSyncPress` or `onAsyncPress`.
If you have to post field like **bookable**, you just need to change the value into wherever you like.  
Maybe following code could be work for you:
```javascript
<Switch
  width={60}
  height={30}
  circleColor={'white'}
  backgroundInactive={'rgba(255,255,255,0.2)'}
  backgroundActive={appColors.green}
  onSyncPress={value => this.props.bookableSwitch(value)}
/>
```
What to do is just to get rid of control from redux. `value` just use default value. Maybe I should prevent component from changing value with props.

**Comment by amhinson** [comment]
How would I get the initial value from redux though?

**Comment by poberwong** [comment]
I've removed function `componentWillReceiveProps` in 0.3.2 which is published. So you can use `this.props.bookable` to initialize value and status of switch will not be changed again by props.

**Comment by amhinson** [comment]
Thanks for working with me on this! Unfortunately that doesn't seem to quite solve it. It seems that the component isn't being rendered with the initial state from props.

`this.props.bookable` is `true` but when I do:
```
value={this.props.bookable}
```
it just defaults to false.

**Comment by poberwong** [comment]
I will go back to BeiJing tomorrow, what you wanna do makes me confused.  
Please reply following questions:
1. Whether you wanna control the switch by mutable props ？
2. Whether you wanna change  status of switch by gesture interaction

**Comment by amhinson** [comment]
I just need the switch to receive props from redux and then be able to change that prop (via redux) and be updated with the new value.

**Comment by poberwong** [comment]
0.4.0 is released with some break changes. What you want is already supported.

**Comment by amhinson** [comment]
Things are getting better! Here is what I'm seeing now:

![screen recording 2017-02-07 at 03 08 pm](https://cloud.githubusercontent.com/assets/17091790/22711605/6ade07b0-ed47-11e6-97d2-a94a93f834c2.gif)

**Comment by poberwong** [comment]
Please give me your code again. I think I will fixed again with this use-case.

**Comment by amhinson** [comment]
```
<Switch
   width={60}
   height={30}
   circleColor={'white'}
   backgroundInactive={'rgba(255,255,255,0.2)'}
   backgroundActive={appColors.green}
   onSyncPress={(value) => this.props.toggleDayAvailability(this.props, day, value);}
   value={dayIsActive(this.props, day.key)}
/>
```
```
const dayIsActive = (props, key) => {
  return _.find(props.availability, ['dow', key]) ? true : false;
};
```
`toggleDayAvailability` basically just sends a request to the server to update that field's value. 

The switches that aren't making any server calls in the `onSyncPress` are working perfectly, but this particular one looks to be getting updated with new props which causes the animation to happen twice.

**Comment by poberwong** [comment]
You can try 0.4.5 on npm and it could be resolved.
