### ISSUE TITLE
Circle color does not work

### ISSUE THREAD

**Issue by Germinate** [poberwong/react-native-switch-pro#10]
Hi. I meet a problem when using this component on **Android**. 
`<Switch circleColorActive="blue" circleColorInactive="black" />`
The circle remains white either the switch is active or inactive. Is my code wrong?
I use React Native 0.41 running on Android 4.4.

**Comment by Germinate** [comment]
I find the problem. Because the lib I downloaded from npm is not the newest code, only find props `circleColor` in the component. When will you update the version on the npm?

**Comment by poberwong** [comment]
0.4.5 has already upload to npm
