### ISSUE TITLE
PropTypes import

### ISSUE THREAD

**Issue by VinceBT** [poberwong/react-native-switch-pro#12]
PropTypes is not imported from React anymore but with

```import PropTypes from 'prop-types'```

**Comment by wangweifeng66** [comment]
中间圆形按钮的半径怎么设置

**Comment by poberwong** [comment]
@wangweifeng66 Please create a new issue to describe the question.

**Comment by poberwong** [comment]
@VinceBT I will fix it tonight

**Comment by jjdp** [comment]
update?

**Comment by poberwong** [comment]
@jjdp Already fixed
