### ISSUE TITLE
weird color on toggle off

### ISSUE THREAD

**Issue by spearmootz** [poberwong/react-native-switch-pro#15]
toggle on looks great but toggle off renders like a yellowish color in the middle. not sure how i can get rid of it.

here is my code

```
const Style = StyleSheet.create({
  switch: {
    marginRight: 8,
    marginLeft: 5
  }
});

<Switch style={Style.switch} value={value} onAsyncPress={onValueChange} backgroundActive='#00b3e3' />```

**Comment by poberwong** [comment]
It's caused by following code in source code. I'm not sure whether switch of backgroundColor needs to be changed with animation. If you set backgroundColor as green, the middle color will be pink and it is just a middle color between `backgroundInactive` and `backgroundActive`.
```javascript
const interpolatedBackgroundColor = switchAnimation.interpolate({
  inputRange: value ? [-this.offset, -1]: [1, this.offset],
  outputRange: [backgroundInactive, backgroundActive]
})
```

**Comment by spearmootz** [comment]
@poberwong yes, i noticed this. Im using the button sync function so i just set both backgroundInactive and backgroundActive to be the same color if my switch state is false.

**Comment by poberwong** [comment]
Yeah，It's one of solutions and it could be better to remove animation on backgroundColor
