### ISSUE TITLE
Error: inputRange must be monotonically increasing

### ISSUE THREAD

**Issue by andreystarkov** [poberwong/react-native-switch-pro#16]
If i set custom values for height / weight in some case i get this error:

```Error: inputRange must be monotonically increasing```

**Comment by poberwong** [comment]
Could u please show your code ?

**Comment by gigeos** [comment]
I have the same problem with this code:
`<Switch height={42}/>`

but this works:
`<Switch width={80} height={42}/>`

**Comment by poberwong** [comment]
1.0.0-beta is released here @gigeos @andreystarkov  , please test the issue on it.
