### ISSUE TITLE
adding 'inActiveText' and 'activeText' to props

### ISSUE THREAD

**Issue by assafb81** [poberwong/react-native-switch-pro#23]
I like your package but I need to do something like this, with your package:
![image](https://user-images.githubusercontent.com/28925534/37773723-05eec84e-2de7-11e8-89ec-1af73d7a991a.png)

the circle switches are ok.
But how can I do the textual switch, the selected value is blue and the unselected is white?

Thanks

**Comment by poberwong** [comment]
I don't think it is necessary to add text feature to switch
