### ISSUE TITLE
Sync or aSync when integrating with Redux

### ISSUE THREAD

**Issue by assafb81** [poberwong/react-native-switch-pro#24]
Hi,
I want to integrate this package in my App.
I am using REDUX and I wonder what is the  option to use:
`onSyncPress` or `onAsyncPress`?

**Comment by poberwong** [comment]
It depends on whether the task is asynchronous not frame you use. If your task is based on network request, you should better use onAsyncPress because it will hold on several millisecond and maybe it will fail.
