### ISSUE TITLE
Switch Toggle Not Working Properly.

### ISSUE THREAD

**Issue by diaojinggang** [poberwong/react-native-switch-pro#25]
https://github.com/poberwong/react-native-switch-pro/blob/e0cb3e8b99f3fe7b9910f5fc0e41d65918e0309b/lib/index.js#L59

The issue I am facing is shown in the gif.
<img src="https://media.giphy.com/media/27bOpTpXNBNznYlzNT/giphy.gif" width=200>

This issue starts to happen after I updated all my react-native packages to the newest. It worked fine before. My current workspace versions:
```
    "expo": "^25.0.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
```
My related code is simplified as following:
```javascript
export default class someComponet extends Component {

createSwitch(value, onSyncPress) {
    return (
        <View style={{paddingTop:20}}>
            <Switch
                height={25}
                width={50}
                onSyncPress={onSyncPress}
                value={value}
            />
       </View>
    )
};

<Modal visible=true>
    <View>
        {this.createSwitch(
            this.state.myTestState,
            (val) => {this.setState({myTestState:val})}
          )}
     </View>
</Modal>

}
```

After checking the logic, I feel there isn't any obvious issue with my code. I noticed you are implementing `componentWillReceiveProps` in this way:
```javascript
componentWillReceiveProps (nextProps) {
    if (nextProps === this.props) {
      return
    }

    // componentWillReceiveProps will still be triggered if
    // render function of father component is triggered.
    // Thus, toggleSwitch will be executed without two-way bind.
    if (typeof nextProps.value !== 'undefined' && nextProps.value !== this.props.value) {
      /** you can add animation when changing value programmatically like following:
      /* this.animateHandler(this.handlerSize * SCALE, () => {
      /*   this.toggleSwitch(true)
      /*  })
       **/
      this.toggleSwitch(true)
    }
  }
```
`toggleSwitch(true)` does the animation of the switching. However, this function may be called both in `componentWillReceiveProps` and `_onPanResponderRelease` given the condition `(nextProps.value !== this.props.value)`. Calling `toggleSwitch(true)` twice is why the issue is happening to me.

I commented out all code in `componentWillReceiveProps` and the switch worked properly. Could you explain the details about`componentWillReceiveProps`? Why do you need the following line and why is `toggleSwitch(true)` called twice in my case?
```javascript
    if (typeof nextProps.value !== 'undefined' && nextProps.value !== this.props.value) {
      this.toggleSwitch(true)
    }
```

----------------------------------
update on March 24, 2018, I checked your previous commit. For example in this one 078ba2971eaa3260c78678b9a35d65072d2c9aa4 on Dec 7, 2017, `componentWillReceiveProps` works perfectly on my code in this version, even with update a switch with programming approach. So you can close my issue now. However, this makes me feel your current `componentWillReceiveProps` may have issues for other users as well.

In the gif, the behavior of the code when I just do a single click is  
1. toggleSwitch from _onPanResponderRelease; toValue: true 
2. toggleSwitch from componentWillReceiveProps, toValue: false 

Seems when `componentWillReceiveProps` is triggered, nextProps has not become the current props and you have no control over when `componentWillReceiveProps` will be triggered in my code. Explicitly doing `setState({val: nextProps.val})` should be safer then a boolean flip.
```javascript
  componentWillReceiveProps (nextProps) {
    if (typeof nextProps.value !== 'undefined' && nextProps.value !== this.props.value) {
      this.animateSwitch(nextProps.value, () => {
        this.setState({ value: nextProps.value })
      })
    }
  }
```

**Comment by poberwong** [comment]
Ok, I will review the lib and fix it in two days. Thanks for your work. Maybe I should do some test before release

**Comment by poberwong** [comment]
I'm sorry that I didn't fix the bug due to limited time, **u'd better use 0.4.8 instead for the moment**. and I will fix it on the weekend.

**Comment by Danjavia** [comment]
Some advance in this issue?

**Comment by meurling** [comment]
I am also facing this issue!

**Comment by ahmedu007** [comment]
Please accept the pull request. This is a really annoying bug

**Comment by poberwong** [comment]
already fixed. thank u . @diaojinggang @ahmedu007 @meurling @sebirdman @Danjavia
