### ISSUE TITLE
Double tap causes the circle to disappear

### ISSUE THREAD

**Issue by efournival** [poberwong/react-native-switch-pro#28]
The circle "leaves" the background just like it has gone too far.
If you tap the switch again it comes back at the right place.
This is easily reproducible but I can make a gif if needed.
Thanks for this library

**Comment by atitpatel** [comment]
Facing the similar issue!!!!

**Comment by chyi13** [comment]
+1

**Comment by RossKinsella** [comment]
Seeing this also:

Gif:
https://cl.ly/1Y3M3k1v2N0M

Code:
```
                  <Switch
                    value={canChat}
                    onSyncPress={setCanChat}
                  />
```

**Comment by RossKinsella** [comment]
This appears to be an issue with two way data binding for me. When I remove my onSyncPress, which triggers an API request and later sets the canChat value, it does not have the behaviour in my gif

**Comment by poberwong** [comment]
Oh，it seems very  serious issue.
