### ISSUE TITLE
Programatically binding value to Switch is broken

### ISSUE THREAD

**Issue by adammcarth** [poberwong/react-native-switch-pro#29]
Hey @poberwong. First of all, thanks for making this library. There's loads of great options here for customising toggles, so thanks for everything so far!

I believe I've found a bug with the two directional binding of a `value` to toggles. It seems to me that this functionality, at least on Android, is not currently working at all - and based off my testing I think it was broken since version 0.4.9 (b410466).

### What's breaking?

The toggle buttons work perfectly, until you try to bind a `value` to programatically set the position of the toggle.

#### Version 0.4.8*
Toggles, and two directional binding, work correctly as expected.

![Working 1](https://imgkk.com/i/ybe0.jpg)
![Working 2](https://imgkk.com/i/r_sk.jpg)

#### Version 0.4.9 & Version 0.4.10
Toggles snap back into the off state every time they are pressed.

![Working 1](https://imgkk.com/i/ybe0.jpg)
![Working 2](https://imgkk.com/i/r_sk.jpg)
![Working 1](https://imgkk.com/i/ybe0.jpg)

#### Version 0.4.11 (latest)
The state of toggles is set correctly by `value`, but the toggles break visually. The background colour turns to a weird mixture of blue and (red?), and the circle floats outside of the toggle container.

![Working 1](https://imgkk.com/i/ybe0.jpg)
![Failing 2](https://imgkk.com/i/s15t.jpg)
![Failing 3](https://imgkk.com/i/ixzi.jpg)

### Demo Code:

```jsx
import React from 'react'; // 16.3.1
import { View, Text } from 'react-native'; // 0.55.3
import Switch from 'react-native-switch-pro';

export default class SwitchyApp extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      on: false,
    };

    // Bind `this` to our 2 helper functions
    this._onSyncPress = this._onSyncPress.bind(this);
    this._turnOffSwitch = this._turnOffSwitch.bind(this);
  }

  _onSyncPress() {
    // Using timeout to show delay in the initial onPress animation
    // and the state change (causing the bug)
    setTimeout(() => {
      this.setState({
        // @BUG This causes render issues
        on: !this.state.on,
      });
    }, 1000);
  }

  // Another use-case of two directional binding, which also fails
  // to work properly...
  _turnOffSwitch() {
    this.setState({
      // @BUG This causes render issues
      on: false,
    });
  }

  render() {
    return (
      <View style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#0D0D0D',
      }}>
        <Text onPress={() => this._turnOffSwitch()}>Turn Off!</Text>

        <Switch
          width={51}
          height={32}
          circleStyle={{width: 28, height: 28}}
          backgroundActive="#EE3094"
          backgroundInactive="#DDD"
          onSyncPress={() => this._onSyncPress()}
          value={this.props.on}
        />
      </View>
    );
  }
}
```

I've replicated the bug on Google Pixel 2 XL, and a Samsung Galaxy S7 both running Android 8.1.0. I don't believe it's going to be a device specific issue though. You should be able to reproduce the issue (with the code above) on any device or operating system.

Anyone got any ideas?

Adam.

**Comment by atitpatel** [comment]
@adammcarth  This is what worked for me. You should also try it :

```
_onAsyncPress(){
    setTimeout(() => {
           this.setState({
        on: !this.state.on,
      });
    }, 1000);
     this.setState({
        on: this.state.on
     });
     
      // Before the timeout completes, your switch will be toggled on and then setTimout will toggle it 
     // back to initial state.
  }
```

**Comment by poberwong** [comment]
1.0.0-beta is released here @adammcarth  , please test the issue on it.
