### ISSUE TITLE
Why its in Beta version for long time?

### ISSUE THREAD

**Issue by galeels** [poberwong/react-native-switch-pro#41]
Hi,
Thanks for this nice package and making it OSS.

In my company we have policy of not using beta packages for production build. And this package has lot of fixes covered in beta release and it's been a long time since this package is tagged under beta.

May I know when this package will release with major version(without Beta)? Like me, others might not use this package. Can you take this on priority?

**Comment by poberwong** [comment]
Ok, It's time to release to 1.0 and thank you for reminding me.

**Comment by poberwong** [comment]
Version has already changed to 1.0.2.

**Comment by galeels** [comment]
Thanks a lot.
