### ISSUE TITLE
To the author: You are probably being impersonated

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [poberwong/react-native-switch-pro#48]
This is what I got today in my mailbox:

![image](https://user-images.githubusercontent.com/7723097/76157029-fdf3dd80-6135-11ea-9194-d981f257d942.png)

SSH key sharing is out of question here, no?

**Comment by poberwong** [comment]
That's me, I'm not impersonated. I just need help to complete some tests of our system. you can replace the old one with a new ssh key on your github before sharing.
Thank you.

**Comment by yurakruhlyk** [comment]
@poberwong you can just create a new account. 💁
