### ISSUE TITLE
Weird UI behavior while using onAsyncPress

### ISSUE THREAD

**Issue by nataroo** [poberwong/react-native-switch-pro#9]
I use onAsyncPress for callback.  As soon as I tap the switch, the switch animates to a weird state, the circle kind of drags as if it is going to animate but not completely.  callback(true) sets the UI right.  But if I don't want to change the value of the switch and cancel the action, it remains in that weird state.

**Comment by poberwong** [comment]
The problem may be solved on 0.4.5. please try again.
